baseURL: "https://jeffreyfisher.net/"
languageCode: "en-us"
title: "Jeffrey Fisher"

theme: "PaperMod"

# Theme parameters
params:
  defaultTheme: "auto"
  showReadingTime: true
  showToc: true
  showCodeCopyButtons: true

  homeInfoParams:
    Title: "Jeffrey Fisher's Website and Blog"
    Content: |
      email: `jeffrey@jeffreyfisher.net` ([mailto link](mailto:jeffrey@jeffreyfisher.net))

  socialIcons:
    - name: "rss"
      url: "/index.xml"
    - name: "github"
      url: "https://github.com/jegfish"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    # - name: "About"
    #   weight: 1
    #   url: "about/"
    # - name: "Blog"
    #   weight: 2
    #   url: "posts/"
    - name: "Projects"
      weight: 2
      url: "projects/"
    - name: "Archive"
      weight: 3
      url: "archive/"
    - name: "Search"
      weight: 4
      url: "search/"
