baseURL = "https://example.org/"
languageCode = "en-us"
title = "Jeffrey Fisher"
copyright = ""
theme = "hugo-bearcub"
defaultContentLanguage = "en"


[menus]
  # [[menus.main]]
  #   name = 'Products'
  #   pageRef = '/products'
  #   weight = 10

[params]
  description = "Bear Cub Demo"

  title = "Jeffrey Fisher"

  madeWith = "Made with [Hugo](https://gohugo.io/) and [Hugo Bear Cub theme](https://github.com/clente/hugo-bearcub)"

  dateFormat = "2006-01-02"

#   [params.author]
#     name = "Jeffrey Fisher"
#     email = "jeffrey@jeffreyfisher.net"
