* Setup
First, clone the repo.

Then, initialize:

#+begin_src sh
  make setup
#+end_src
* todolist
** TODO Build PDFs
*** TODO Build PDFs
*** TODO Build collated PDF of all pages
At least all articles. If possible also other pages like About.

*** TODO Add link to all pages to get PDF version of it
Part of a template so don't have to manually write it on all the pages.

At least have this thing show up on blog posts.

** TODO Try to get RSS to include full articles
If it's a pain, not gonna try too hard on this one.

* Bug log

** 2023-06-05 GitHub Actions runner returns success, but get 404
Actions runner logs also seem to be fine.

I notice in the Pages settings that the custom domain field is empty, though the custom domain is setup.

*** Attempt: Fill out the custom domain field and rerun Action
Success.

I believe the problem was that the =CNAME= file disappeared. It is stored in the =docs/= directory. I will try ensuring that the CNAME file exists using Makefile. It gets deleted when I run the Hugo build.

This seems to fix it.

* Sources
** Math typesetting
https://adityatelange.github.io/hugo-PaperMod/posts/math-typesetting/
** Make a non-blog post
https://github.com/adityatelange/hugo-PaperMod/issues/26#issuecomment-704321127

Technically it's easy to make a non-blog post, but the part I couldn't figure out was not showing name/publish date.

This is accomplished with the =hidemeta: true= configuration option.
